### ISSUE TITLE
Javascript error when trying to post text update

### ISSUE THREAD

**Issue by nickgeorgiou** [cmcnamara87/progress#30]
I get this error: 

TypeError: Cannot read property 'length' of null
    at k.m [as postUpdate](http://cmcnamara87.github.io/progress/scripts/d7dd1810.scripts.js:1:5390)
    at http://cmcnamara87.github.io/progress/scripts/f362672b.vendor.js:6:29525
    at http://cmcnamara87.github.io/progress/scripts/f362672b.vendor.js:7:4569
    at k.$eval (http://cmcnamara87.github.io/progress/scripts/f362672b.vendor.js:5:25742)
    at k.$apply (http://cmcnamara87.github.io/progress/scripts/f362672b.vendor.js:5:26020)
    at HTMLButtonElement.<anonymous> (http://cmcnamara87.github.io/progress/scripts/f362672b.vendor.js:7:4551)
    at HTMLButtonElement.eb.event.dispatch (http://cmcnamara87.github.io/progress/scripts/f362672b.vendor.js:2:17661)
    at HTMLButtonElement.q.handle (http://cmcnamara87.github.io/progress/scripts/f362672b.vendor.js:2:14341) f362672b.vendor.js:5

**Comment by cmcnamara87** [comment]
It's nice to get these issue reports :)
